### ISSUE TITLE
Support earlier node versions

### ISSUE THREAD

**Issue by acrisci** [acrisci/node-dbus-next#6]
Try to support earlier node versions by hiding new language features for versions that don't support them.

@CyDragon80 proposed a solution here: https://github.com/sidorares/dbus-native/pull/251#issuecomment-460656169

```javascript
function getNodeMajor()
{
    var reg = /^[^\d]*(\d+)/;
    var temp = reg.exec(process.version);
    return (temp==null||temp[1]==null?0:parseInt(temp[1]));
}
module.exports.NodeMajor = getNodeMajor(); // only need to compute once
. . .
if (module.exports.NodeMajor >= 7)
{
    // new feature just for 7+
    const OptionalBit = require('optional-bit'); // module containing newer language features
    module.exports.newThing = OptionalBit.newThing; // new package feature export
    // etc etc
}
else
{
    // fallback if any? or leave new stuff undefined?
    module.exports.newThing = null; // ?
    module.exports.newThing = function() { throw new Error('Feature needs Node 7+')}; // ?
}
```

**Comment by acrisci** [comment]
There might be a better way to do this, like using polyfills, especially for bigint, and maybe publish a babel-transpiled version that works with earlier nodes. Not sure what people do here.

**Comment by CyDragon80** [comment]
Ya, the backwards compatibility dance gets interesting. At what point do you make a clean break, do you do a major rev or new package, do you just limit yourself to the [lowest common denominator](https://node.green/) that you need to support or try polyfill/transpiling, do you cut off support based on the [node support cycles](https://github.com/nodejs/Release), etc. Whatever policy one adapts, it is probably important to be upfront about it and clear what the node requirements are for particular packages/versions.

**Comment by acrisci** [comment]
I haven't really assessed what versions I want to support yet. The main thing I want to do with this is to get better integration of electron apps with the Linux Desktop, and I haven't looked at what node versions they want to use.

If you have a use case in mind for earlier node versions, I will strongly consider supporting them if it's practical.

**Comment by rocka** [comment]
We can use [big-integer](https://www.npmjs.com/package/big-integer) as a wrapper for BigInt operations. Both support earlier Node versions and make use of native BigInt in newer Noder versions.

Currently, Electron 3.x (with Node 10.2.0) dose not support BigInt ... sad :(

**Comment by acrisci** [comment]
Yeah sounds good. Let's try to support that version then.

**Comment by acrisci** [comment]
is `8.2.1` low enough?

See 07902baf for the recent compatibility work.

**Comment by rocka** [comment]
Electron 1.8.x is using Node 8.2.1, that's a pretty old version.

and I've successfully started my little program on Electron 3.1.3 with [`dbus-next@9a6389b`](https://github.com/acrisci/node-dbus-next/commit/9a6389bcd35dd0fb278eecf98163360d38634a92). Cheers! 🎉

**Comment by acrisci** [comment]
:+1: if you have a use case for earlier versions open a new issue with the version you want supported. I think this works for me right now.

**Comment by acrisci** [comment]
My test suite is now passing with 6.3.0.
